# Generated by Django 5.1.4 on 2024-12-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_all', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('photo', models.ImageField(blank=True, default='profiles/traveldefualt.jpg', upload_to='profiles')),
                ('destination', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('Budget-friendly', 'Budget-friendly'), ('Fancy', 'Fancy')], max_length=200)),
                ('start_place', models.CharField(max_length=200)),
                ('transportation', models.CharField(choices=[('Train', 'Train'), ('Bus', 'Bus'), ('Plane', 'Plane'), ('Car', 'Car')], max_length=200)),
                ('end_date', models.DateField()),
                ('travellers', models.IntegerField(default=5)),
                ('empty_travellers', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=200)),
                ('rate', models.IntegerField(default=0)),
                ('rated_by', models.IntegerField(default=0)),
                ('key', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravellersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TravelUserRateMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TravelUserRateSleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_rated_by', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
