# Generated by Django 5.0.7 on 2024-11-12 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('photo', models.ImageField(upload_to='profiles')),
                ('destination', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('Budget-friendly', 'Budget-friendly'), ('Fancy', 'Fancy')], max_length=200)),
                ('start_place', models.CharField(max_length=200)),
                ('transportation', models.CharField(choices=[('Train', 'Train'), ('Bus', 'Bus'), ('Plane', 'Plane'), ('Car', 'Car')], max_length=200)),
                ('end_date', models.DateField()),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
