# Generated by Django 5.0.7 on 2024-11-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0002_alter_travel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
