# Generated by Django 5.0.7 on 2024-11-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0003_alter_travel_end_date'),
        ('editprofile', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='editprofile.userprofile'),
        ),
    ]
