# Generated by Django 5.0.7 on 2024-11-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0005_travel_travellers_alter_travel_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_all', models.EmailField(max_length=254)),
            ],
        ),
    ]
