# Generated by Django 5.0.7 on 2024-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0006_emailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email_all',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
