# Generated by Django 5.0.7 on 2024-11-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0007_alter_emailaddress_email_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_date',
            field=models.DateField(),
        ),
    ]
