# Generated by Django 5.0.7 on 2024-11-25 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0008_alter_travel_end_date_alter_travel_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TravellersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('travel_is', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='travel_group', to='Travels.travel')),
                ('users', models.ManyToManyField(related_name='travel_group_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_rate', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('r_travel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='travel_rate', to='Travels.travel')),
            ],
        ),
        migrations.CreateModel(
            name='UserRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_rate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
