# Generated by Django 5.0.7 on 2024-11-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0009_alter_travel_admin_travellersgroup_travelrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travellersgroup',
            name='group_name',
        ),
    ]
