# Generated by Django 5.0.7 on 2024-11-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0010_remove_travellersgroup_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='empty_travellers',
            field=models.IntegerField(default=1),
        ),
    ]
