# Generated by Django 5.0.7 on 2024-11-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0011_travel_empty_travellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
