# Generated by Django 5.0.7 on 2024-11-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0014_userrate_rated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrate',
            name='rate',
        ),
    ]
