# Generated by Django 5.0.7 on 2024-11-27 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0015_remove_userrate_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrate',
            name='rated_by',
        ),
        migrations.AddField(
            model_name='userrate',
            name='rated_by',
            field=models.ManyToManyField(blank=True, related_name='rated_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
