# Generated by Django 5.0.7 on 2024-11-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0016_remove_userrate_rated_by_userrate_rated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrate',
            name='number_rated_by',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
