# Generated by Django 5.0.7 on 2024-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0017_userrate_number_rated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrate',
            name='travel_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
