# Generated by Django 5.0.7 on 2024-11-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0018_alter_travelrate_travel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TravelRate',
        ),
    ]
