# Generated by Django 5.0.7 on 2024-11-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0019_travel_rate_delete_travelrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='rated_by',
            field=models.IntegerField(default=0),
        ),
    ]
