# Generated by Django 5.1.2 on 2024-12-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travels", "0021_travel_rated_by_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel",
            name="photo",
            field=models.ImageField(
                default="profiles/paize2_abK6hhZ.jpg", upload_to="profiles"
            ),
        ),
    ]
