# Generated by Django 5.0.7 on 2024-12-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0022_alter_travel_photo_traveluserrate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traveluserrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='travel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='status',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=200),
        ),
    ]
