# Generated by Django 5.0.7 on 2024-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0023_alter_travel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='photo',
            field=models.ImageField(blank=True, default='profiles/traveldefualt.jpg', upload_to='profiles'),
        ),
    ]
