# Generated by Django 5.0.7 on 2024-12-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0023_alter_traveluserrate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveluserrate',
            name='rate',
            field=models.IntegerField(default=0, help_text='Rate between 1 and 5'),
        ),
    ]
