# Generated by Django 5.0.7 on 2024-12-03 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0024_alter_travel_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelUserRateMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, help_text='Rate between 1 and 5', null=True)),
                ('rated_by', models.ManyToManyField(related_name='ratings_given_money', to=settings.AUTH_USER_MODEL)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings_money', to='Travels.travel')),
                ('user_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received_money', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelUserRateSleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, help_text='Rate between 1 and 5', null=True)),
                ('rated_by', models.ManyToManyField(related_name='ratings_given_sleep', to=settings.AUTH_USER_MODEL)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings_sleep', to='Travels.travel')),
                ('user_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received_sleep', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TravelUserRate',
        ),
    ]
