# Generated by Django 5.1.4 on 2024-12-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0028_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='travel_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
