# Generated by Django 5.1.4 on 2024-12-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0031_travel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='key',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
