# Generated by Django 5.1.2 on 2024-11-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0002_user_bio_user_city_user_first_name_user_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirm_password",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="current_password",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="new_password",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
