# Generated by Django 5.1.2 on 2024-11-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0003_user_confirm_password_user_current_password_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="first_name", new_name="firstName",
        ),
        migrations.RenameField(
            model_name="user", old_name="last_name", new_name="lastName",
        ),
        migrations.RenameField(
            model_name="user", old_name="profile_picture", new_name="profilePicture",
        ),
        migrations.RenameField(
            model_name="user", old_name="user_name", new_name="username",
        ),
        migrations.RemoveField(model_name="user", name="confirm_password",),
        migrations.RemoveField(model_name="user", name="current_password",),
        migrations.RemoveField(model_name="user", name="new_password",),
        migrations.AddField(
            model_name="user",
            name="birthDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
