# Generated by Django 5.0.7 on 2024-11-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_remove_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Female', 'a'), ('Male', 'b')], max_length=10),
        ),
    ]
