# Generated by Django 5.0.7 on 2024-11-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_rename_first_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
