# Generated by Django 5.0.7 on 2024-11-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_user_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
