# Generated by Django 5.0.7 on 2024-11-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_user_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
