# Generated by Django 5.1.2 on 2024-11-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0005_rename_username_user_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
