# Generated by Django 5.1.2 on 2024-11-25 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0006_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="time_add",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
