# Generated by Django 5.1.2 on 2024-11-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0006_alter_user_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="profilePicture", new_name="profile_image",
        ),
    ]
