# Generated by Django 5.0.7 on 2024-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_alter_user_bio_alter_user_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, default='profile_pictures/photo_1_2024-11-22_00-36-00.jpg', upload_to='profile_pictures/'),
        ),
    ]
