# Generated by Django 5.0.7 on 2024-11-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_remove_user_name_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
