# Generated by Django 5.0.7 on 2024-11-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_user_image_url_user_last_name_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
