# Generated by Django 5.0.7 on 2024-12-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_alter_user_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
