# Generated by Django 5.0.7 on 2024-11-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_remove_user_image_url_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
