# Generated by Django 5.1.2 on 2024-11-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0008_remove_user_birth_date_remove_user_city_and_more"),
        ("signup", "0009_remove_user_image_url_remove_user_last_name_and_more"),
    ]

    operations = []
