# Generated by Django 5.0.7 on 2024-11-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_remove_user_birth_date_remove_user_city_and_more'),
        ('signup', '0010_remove_user_birth_date_remove_user_city_and_more'),
    ]

    operations = [
    ]
