# Generated by Django 5.0.7 on 2024-12-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='travel_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
