# Generated by Django 5.0.7 on 2024-11-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('a', 'Female'), ('b', 'male')], max_length=10),
        ),
    ]
