# Generated by Django 5.1.4 on 2024-12-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('Accommodation', 'Accommodation'), ('Entertainment', 'Entertainment'), ('Groceries', 'Groceries'), ('Healthcare', 'Healthcare'), ('Insurance', 'Insurance'), ('Rent & Charges', 'Rent & Charges'), ('Restaurants & Bars', 'Restaurants & Bars'), ('Shopping', 'Shopping'), ('Transport', 'Transport'), ('Other', 'Other')], default='Other', max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(default='payment', max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('receipt_image', models.ImageField(default='/pay.jpg', upload_to='receipts/')),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PastPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
