# Generated by Django 5.1.4 on 2024-12-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Accommodation', 'Accommodation'), ('Entertainment', 'Entertainment'), ('Groceries', 'Groceries'), ('Healthcare', 'Healthcare'), ('Insurance', 'Insurance'), ('Rent & Charges', 'Rent & Charges'), ('Restaurants & Bars', 'Restaurants & Bars'), ('Shopping', 'Shopping'), ('Transport', 'Transport'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
