# Generated by Django 5.0.7 on 2024-12-02 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_remove_expense_created_at_remove_settlement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='settlement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
