# Generated by Django 5.1.2 on 2024-12-02 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_expense_created_at_settlement_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense", old_name="travel", new_name="travel_is",
        ),
        migrations.RenameField(
            model_name="settlement", old_name="travel", new_name="travel_is",
        ),
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(default=datetime.timezone),
        ),
        migrations.AlterField(
            model_name="settlement",
            name="date",
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
