# Generated by Django 5.1.4 on 2024-12-28 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_expense_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastpayment',
            old_name='user',
            new_name='payer',
        ),
        migrations.RemoveField(
            model_name='pastpayment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pastpayment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pastpayment',
            name='expense',
        ),
        migrations.AddField(
            model_name='pastpayment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pastpayment',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pastpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
