# Generated by Django 5.0.7 on 2024-12-04 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0027_alter_traveluserratemoney_rate_and_more'),
        ('planner', '0004_rename_travel_expense_travel_is_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='travel_is',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='travel_is',
        ),
        migrations.AddField(
            model_name='expense',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='Travels.travellersgroup'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='Travels.travellersgroup'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
