# Generated by Django 5.1.4 on 2024-12-28 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0002_initial'),
        ('planner', '0005_rename_user_pastpayment_payer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpayment',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastpay', to='Travels.travellersgroup'),
        ),
    ]
