# Generated by Django 5.0.7 on 2024-12-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_remove_expense_travel_is_remove_settlement_travel_is_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='participants',
        ),
    ]
