# Generated by Django 5.0.7 on 2024-12-04 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_remove_expense_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='participants',
            field=models.ManyToManyField(related_name='shared_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
