# Generated by Django 5.1.4 on 2024-12-28 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_pastpayment_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpayment',
            name='Expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.expense'),
        ),
    ]
