# Generated by Django 5.1.2 on 2024-12-11 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0007_expense_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="title",
            field=models.CharField(default="payment", max_length=100),
        ),
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participating_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="settlement",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
