# Generated by Django 5.1.2 on 2024-12-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0009_expense_category_expense_custom_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="expense", name="category",),
        migrations.RemoveField(model_name="expense", name="custom_category",),
        migrations.RemoveField(model_name="expense", name="description",),
        migrations.RemoveField(model_name="expense", name="participants",),
    ]
