# Generated by Django 5.1.2 on 2024-12-11 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0010_remove_expense_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Accommodation", "Accommodation"),
                    ("Entertainment", "Entertainment"),
                    ("Groceries", "Groceries"),
                    ("Healthcare", "Healthcare"),
                    ("Insurance", "Insurance"),
                    ("Rent & Charges", "Rent & Charges"),
                    ("Restaurants & Bars", "Restaurants & Bars"),
                    ("Shopping", "Shopping"),
                    ("Transport", "Transport"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="participants",
            field=models.ManyToManyField(
                related_name="participant_expenses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payer_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
