# Generated by Django 5.1.2 on 2024-12-11 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0011_expense_category_expense_participants_expense_payer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="expense", name="created_by",),
        migrations.AddField(
            model_name="expense", name="description", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="receipt_image",
            field=models.ImageField(blank=True, null=True, upload_to="receipts/"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Accommodation", "Accommodation"),
                    ("Entertainment", "Entertainment"),
                    ("Groceries", "Groceries"),
                    ("Healthcare", "Healthcare"),
                    ("Insurance", "Insurance"),
                    ("Rent & Charges", "Rent & Charges"),
                    ("Restaurants & Bars", "Restaurants & Bars"),
                    ("Shopping", "Shopping"),
                    ("Transport", "Transport"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="participants",
            field=models.ManyToManyField(
                null=True,
                related_name="participant_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="title",
            field=models.CharField(default="payment", max_length=100, null=True),
        ),
    ]
