# Generated by Django 5.1.2 on 2024-12-12 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0012_remove_expense_created_by_expense_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="participants",
            field=models.ManyToManyField(
                related_name="participant_expenses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
