# Generated by Django 5.1.4 on 2024-12-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_remove_expense_participants_expense_title_and_more'),
        ('planner', '0013_alter_expense_participants'),
    ]

    operations = [
    ]
